### ISSUE TITLE
Checking for Covalent project submission

### ISSUE THREAD

**Issue by xiaogit00** [tans/TinyWallet#1]
Hey! 

Really nice project. Can I check, for TinyWallet, Covalent data is pre-loaded and stored in MongoDB? Are there any backend applications built for this?

It'll be good if I can see evidence that Covalent data is used. 

Thanks lots 

Best,
Leibing
Developer Relations, Covalent

**Comment by tans** [comment]
all you see in tinywallet.app was in this codebase.

we fetch transaction data from  Covalent in  https://github.com/tans/TinyWallet/blob/main/schedule/tx.js

then transfer into token stat data in https://github.com/tans/TinyWallet/blob/main/schedule/radar.js

but the transaction data to large for us, so we just remove it after we have the token transfer logs and stats.

**Comment by tans** [comment]
the code is simple, but works.  the data is up to date behind real-world 2 minutes,  just the same as Covalent. feel free to as me any question 😁

**Comment by xiaogit00** [comment]
amazing! good job guys. Thank you.
